### ISSUE TITLE
It seems queries with high score are not handled.

### ISSUE THREAD

**Issue by jdkim** [your-jiseong/agm_2016#1]

**Comment by your-jiseong** [comment]
By the analysis, AGM is not problem; i.e., it is fine for AGM to sort and ask queries in order of their score in descending order.

The last time, we can not get an answer from the QGM-generated query of the score "0.8" below.

SELECT ?v2 WHERE { 
?v2 ?v8 <http://dbpedia.org/ontology/River> ; 
<http://dbpedia.org/ontology/city> <http://dbpedia.org/resource/Seoul> . }

By the analysis, the reason why the query does not give us an answer is that simply there is no answers for that query in English DBpedia 2015.

The web interface uses "http://143.248.135.20:45103" and "http://en.dbpedia2015-10.kaist.ac.kr" as SPARQL endpoint and default graph-iri respectively; so, if we ask a query to the SPARQL endpoint  with designating "http://en.dbpedia2015-10.kaist.ac.kr" as a default graph-iri, we can check an answer does not exist in English DBpedia 2015. 

If an answer for a query of a high score exists in KB, AGM will successfully give an answer for that query.
